#!/usr/bin/env bash
# Bundle the daemon + config + unit + installer into ONE self-contained script
# you can scp to any client and run:  window-logger-deploy.sh
#
#   ./build-deploy.sh   ->   dist/window-logger-deploy.sh
set -euo pipefail
cd "$(dirname "$(readlink -f "$0")")"

OUT="dist/window-logger-deploy.sh"
mkdir -p dist

emit_file() {  # var-name  path
  local marker="$1" path="$2"
  printf 'base64 -d > "$TMP/%s" <<'\''%s'\''\n' "$(basename "$path")" "$marker"
  base64 "$path"
  printf '%s\n\n' "$marker"
}

{
  cat <<'HEADER'
#!/usr/bin/env bash
# Self-contained window-logger deployer (generated by build-deploy.sh — do not edit).
# Extracts the daemon, example config, systemd unit and installer, then installs.
set -euo pipefail
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/systemd"
HEADER

  emit_file B64_PY   window_logger.py
  emit_file B64_CFG  config.example.toml
  emit_file B64_INS  install.sh

  # the unit must land under systemd/ for install.sh to find it
  printf 'base64 -d > "$TMP/systemd/window-logger.service.in" <<'\''B64_UNIT'\''\n'
  base64 systemd/window-logger.service.in
  printf 'B64_UNIT\n\n'

  cat <<'FOOTER'
chmod +x "$TMP/install.sh"
WL_SRC_DIR="$TMP" bash "$TMP/install.sh"
FOOTER
} > "$OUT"

chmod +x "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
