#!/usr/bin/env bash
# Bundle the daemon + config + unit + installer into ONE self-contained script
# you can scp to any client and run:  window-logger-deploy.sh
#
#   ./build-deploy.sh   ->   dist/window-logger-deploy.sh
set -euo pipefail
cd "$(dirname "$(readlink -f "$0")")"

OUT="dist/window-logger-deploy.sh"
mkdir -p dist

# Stamp the current git version into the bundled daemon, since the bundle has no
# git checkout to read it from at runtime.
VER="$(git rev-parse --short HEAD 2>/dev/null || true)"
DATE="$(git show -s --format=%cs HEAD 2>/dev/null || true)"
STAMP=""
[ -n "$VER" ] && STAMP="$VER ($DATE)"
STAMPED_PY="dist/.window_logger.stamped.py"
sed "s|^_EMBEDDED_VERSION = \"\"|_EMBEDDED_VERSION = \"${STAMP}\"|" \
    window_logger.py > "$STAMPED_PY"

emit_file() {  # marker  target-name  src-path
  local marker="$1" target="$2" path="$3"
  printf 'base64 -d > "$TMP/%s" <<'\''%s'\''\n' "$target" "$marker"
  base64 "$path"
  printf '%s\n\n' "$marker"
}

{
  cat <<'HEADER'
#!/usr/bin/env bash
# Self-contained window-logger deployer (generated by build-deploy.sh - do not edit).
# Extracts the daemon, example config, systemd unit and installer, then installs.
set -euo pipefail
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/systemd"
HEADER

  emit_file B64_PY   window_logger.py     "$STAMPED_PY"
  emit_file B64_CFG  config.example.toml  config.example.toml
  emit_file B64_INS  install.sh           install.sh

  # the unit must land under systemd/ for install.sh to find it
  printf 'base64 -d > "$TMP/systemd/window-logger.service.in" <<'\''B64_UNIT'\''\n'
  base64 systemd/window-logger.service.in
  printf 'B64_UNIT\n\n'

  cat <<'FOOTER'
chmod +x "$TMP/install.sh"
WL_SRC_DIR="$TMP" bash "$TMP/install.sh"
FOOTER
} > "$OUT"

rm -f "$STAMPED_PY"
chmod +x "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes), stamped version: ${STAMP:-<none>}"
